### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'datesList[_this.state.numVisibleDays - 1].date')

### ISSUE THREAD

**Issue by 17nikhil** [skdev24/calendar-event-app#11]
The error occurs only when I stop the expo server and restart it and open the app again (If there is a an active task in the app)

This error is located at:
    in NavigationContainer (at App.js:43)
    in TodoStore
    in App (created by ExpoRoot)
    in ExpoRoot (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)

**Comment by skdev24** [comment]
https://github.com/BugiDev/react-native-calendar-strip/issues/303#issuecomment-864510769
